# #config/validator/validation.yaml
# App\Entity\Contact:
#     properties:
#         email:
#             - NotBlank: ~
#             - Email: { mode: strict }
#         captcha:
#             - Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3: ~